name: demo
 
on: [push]
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
 
    - name: Install lng
      run: |
        npm install -g @lightningjs/cli || echo "lng installation via npm failed"
        npm install -g typescript
        lng --version
 
    - name: Install dependencies
      run: npm install
      working-directory: ./
 
    - name: Create dist
      run: lng dist
      working-directory: ./
 
    - name: Commit and Push dist folder
      run: |
        git config --global user.email "santhoshichimakurthi@gmail.com"
        git config --global user.name "santhoshichimakurthi"
        git add ./dist
        git commit -m "Add dist folder"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
