name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install
           npm --version
           lng dist

    - name: Commit and Push dist folder
      run:
        git config --global user.email "santhoshichimakurthi@gmail.com"
        git config --global user.name "santhoshichimakurthi"
        git add ./accelerator-home-ui/dist
        git commit -m "Add dist folder"
        git push origin main
