name: trigger
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: repo checkout
        uses: actions/checkout@v2
      - name: install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install dependencies
        run: npm install -g @lightningjs/cli
      - name: check lng version
        run: lng --version
      - name: install node modules
        run: npm install
        working-directory: ./
      - name: create lng build
        run: lng build
        working-directory: ./
      - name: Commit and Push dist folder
        run:
          git config --global user.email "santhoshichimakurthi@gmail.com"
          git config --global user.name "santhoshichimakurthi"
          git add .
          git commit -m "Add dist folder"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TESTGIT_TOKEN }}
