name: Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install -g @lightningjs/cli

    - name: Version print
      run: lng --version
           chdir
           npm install
    - name: Commit and Push node modules folder
      run:
        git config --global user.email "santhoshichimakurthi@gmail.com"
        git config --global user.name "santhoshichimakurthi"
        git add .
        git status
        git commit -m "Adding changes"
        

      
      
        

    
